# Generated by Django 5.2.6 on 2025-09-27 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('trikego_user', models.CharField(choices=[('M', 'Mobile'), ('A', 'Admin'), ('D', 'Driver')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user')),
                ('position', models.CharField(max_length=100)),
                ('date_hired', models.DateField()),
                ('years_of_service', models.IntegerField()),
            ],
            bases=('login.user',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user')),
                ('license_number', models.CharField(max_length=20)),
                ('license_expiry', models.DateField()),
                ('date_hired', models.DateField()),
                ('years_of_service', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            bases=('login.user',),
        ),
    ]
