# Generated by Django 5.2.6 on 2025-10-13 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Driver Assignment'), ('accepted', 'Driver Accepted'), ('on_the_way', 'Driver On The Way'), ('started', 'Trip Started'), ('completed', 'Completed'), ('cancelled_by_rider', 'Cancelled by Rider'), ('cancelled_by_driver', 'Cancelled by Driver'), ('no_driver_found', 'No Driver Found')], default='pending', max_length=20)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_bookings', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(limit_choices_to={'user_type': 'rider'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
