# Generated by Django 5.2.6 on 2025-10-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.rider'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
