# Generated by Django 5.2.6 on 2025-10-30 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_add_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver'], name='booking_boo_driver__ce5920_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['rider'], name='booking_boo_rider_i_eb21d8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_time'], name='booking_boo_booking_695c61_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver', 'status'], name='booking_boo_driver__3a6065_idx'),
        ),
    ]
