# Generated by Django 5.2.6 on 2025-10-31 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_add_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff')], max_length=8)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('CURRENT', 'Current'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=10)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='booking.booking')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'indexes': [models.Index(fields=['booking', 'sequence'], name='booking_boo_booking_5ef9c5_idx'), models.Index(fields=['status'], name='booking_boo_status_487738_idx')],
            },
        ),
    ]
