# Generated by Django 5.2.6 on 2025-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='trikego_user',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
