# Generated by Django 5.2.6 on 2025-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_driver_is_available_driver_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='trikego_user',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_image_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
