# Generated by Django 5.2.6 on 2025-10-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_admin_user_customuser_trikego_user_driver_user_and_more'),
    ]

    operations = [
    ]
