# Generated by Django 5.2.6 on 2025-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20251004_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
