# Generated by Django 5.2.6 on 2025-10-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_admin_user_alter_customuser_phone_and_more'),
        ('user', '0007_driver_license_image_url'),
    ]

    operations = [
    ]
