# Generated by Django 5.2.6 on 2025-10-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_driver_is_verified_driver_status_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
    ]
