# Generated by Django 5.2.6 on 2025-10-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_driver_current_latitude_driver_current_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
