# Generated by Django 5.2.6 on 2025-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_merge_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('In_trip', 'In trip')], default='Offline', max_length=16),
        ),
    ]
