# Generated by Django 5.2.6 on 2025-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_add_tricycle_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tricycle',
            name='cr_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Certificate of Registration (CR)'),
        ),
        migrations.AddField(
            model_name='tricycle',
            name='mtop_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='MTOP/Franchise Document'),
        ),
        migrations.AddField(
            model_name='tricycle',
            name='or_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Official Receipt (OR)'),
        ),
    ]
