# Generated by Django 5.2.6 on 2025-10-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'trikego_user': 'D'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rider',
            field=models.ForeignKey(limit_choices_to={'trikego_user': 'R'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
