# Generated by Django 5.2.6 on 2025-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Driver Assignment')], default='pending', max_length=20),
        ),
    ]
