# Generated by Django 5.2.6 on 2025-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rider_current_latitude_rider_current_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In_trip', 'In trip')], default='Available', max_length=12),
        ),
    ]
