# Generated by Django 5.2.6 on 2025-10-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('In_trip', 'In trip'), ('pending_approval', 'Pending Approval')], default='Offline', max_length=16),
        ),
        migrations.CreateModel(
            name='Tricycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32, unique=True)),
                ('color', models.CharField(max_length=32)),
                ('capacity', models.IntegerField(default=3)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricycles', to='user.driver')),
            ],
        ),
    ]
