# Generated by Django 5.2.6 on 2025-10-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_driver_status_tricycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tricycle',
            name='capacity',
        ),
        migrations.AlterModelTable(
            name='tricycle',
            table='tricycle',
        ),
    ]
